// Auto-generated by Supabase CLI. Run 'npx supabase gen types typescript --project-id dwlopmxtiokdvjjowfke > lib/supabase/types.ts' to regenerate after schema changes.
// NOTE: This is a placeholder. Replace with generated output after running: supabase db push && npx supabase gen types typescript --project-id dwlopmxtiokdvjjowfke > lib/supabase/types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      email_sequenzen: {
        Row: {
          aktiv: boolean
          betreff: string | null
          created_at: string
          delay_hours: number
          html_body: string | null
          id: string
          produkt_id: string | null
          trigger: string | null
          updated_at: string
        }
        Insert: {
          aktiv?: boolean
          betreff?: string | null
          created_at?: string
          delay_hours?: number
          html_body?: string | null
          id?: string
          produkt_id?: string | null
          trigger?: string | null
          updated_at?: string
        }
        Update: {
          aktiv?: boolean
          betreff?: string | null
          created_at?: string
          delay_hours?: number
          html_body?: string | null
          id?: string
          produkt_id?: string | null
          trigger?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'email_sequenzen_produkt_id_fkey'
            columns: ['produkt_id']
            isOneToOne: false
            referencedRelation: 'produkte'
            referencedColumns: ['id']
          },
        ]
      }
      einstellungen: {
        Row: {
          beschreibung: string | null
          id: string
          schluessel: string
          updated_at: string
          updated_by: string | null
          wert: string | null
        }
        Insert: {
          beschreibung?: string | null
          id?: string
          schluessel: string
          updated_at?: string
          updated_by?: string | null
          wert?: string | null
        }
        Update: {
          beschreibung?: string | null
          id?: string
          schluessel?: string
          updated_at?: string
          updated_by?: string | null
          wert?: string | null
        }
        Relationships: []
      }
      generierter_content: {
        Row: {
          content: Json | null
          created_at: string
          generated_at: string
          id: string
          meta_desc: string | null
          meta_title: string | null
          page_type: string
          produkt_id: string
          published_at: string | null
          schema_markup: Json | null
          slug: string | null
          status: string
          title: string | null
          updated_at: string
        }
        Insert: {
          content?: Json | null
          created_at?: string
          generated_at?: string
          id?: string
          meta_desc?: string | null
          meta_title?: string | null
          page_type: string
          produkt_id: string
          published_at?: string | null
          schema_markup?: Json | null
          slug?: string | null
          status?: string
          title?: string | null
          updated_at?: string
        }
        Update: {
          content?: Json | null
          created_at?: string
          generated_at?: string
          id?: string
          meta_desc?: string | null
          meta_title?: string | null
          page_type?: string
          produkt_id?: string
          published_at?: string | null
          schema_markup?: Json | null
          slug?: string | null
          status?: string
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'generierter_content_produkt_id_fkey'
            columns: ['produkt_id']
            isOneToOne: false
            referencedRelation: 'produkte'
            referencedColumns: ['id']
          },
        ]
      }
      leads: {
        Row: {
          confluence_page_id: string | null
          confluence_synced: boolean
          created_at: string
          email: string
          id: string
          interesse: string | null
          intent_tag: string | null
          nachname: string | null
          produkt_id: string | null
          resend_sent: boolean
          telefon: string | null
          vorname: string | null
          zielgruppe_tag: string | null
        }
        Insert: {
          confluence_page_id?: string | null
          confluence_synced?: boolean
          created_at?: string
          email: string
          id?: string
          interesse?: string | null
          intent_tag?: string | null
          nachname?: string | null
          produkt_id?: string | null
          resend_sent?: boolean
          telefon?: string | null
          vorname?: string | null
          zielgruppe_tag?: string | null
        }
        Update: {
          confluence_page_id?: string | null
          confluence_synced?: boolean
          created_at?: string
          email?: string
          id?: string
          interesse?: string | null
          intent_tag?: string | null
          nachname?: string | null
          produkt_id?: string | null
          resend_sent?: boolean
          telefon?: string | null
          vorname?: string | null
          zielgruppe_tag?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'leads_produkt_id_fkey'
            columns: ['produkt_id']
            isOneToOne: false
            referencedRelation: 'produkte'
            referencedColumns: ['id']
          },
        ]
      }
      produkt_config: {
        Row: {
          anbieter: string[] | null
          argumente: Json | null
          created_at: string
          fokus: string | null
          id: string
          produkt_id: string
          updated_at: string
          zielgruppe: string[] | null
        }
        Insert: {
          anbieter?: string[] | null
          argumente?: Json | null
          created_at?: string
          fokus?: string | null
          id?: string
          produkt_id: string
          updated_at?: string
          zielgruppe?: string[] | null
        }
        Update: {
          anbieter?: string[] | null
          argumente?: Json | null
          created_at?: string
          fokus?: string | null
          id?: string
          produkt_id?: string
          updated_at?: string
          zielgruppe?: string[] | null
        }
        Relationships: [
          {
            foreignKeyName: 'produkt_config_produkt_id_fkey'
            columns: ['produkt_id']
            isOneToOne: false
            referencedRelation: 'produkte'
            referencedColumns: ['id']
          },
        ]
      }
      produkte: {
        Row: {
          created_at: string
          domain: string | null
          id: string
          name: string
          slug: string
          status: string
          typ: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          domain?: string | null
          id?: string
          name: string
          slug: string
          status?: string
          typ: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          domain?: string | null
          id?: string
          name?: string
          slug?: string
          status?: string
          typ?: string
          updated_at?: string
        }
        Relationships: []
      }
      wissensfundus: {
        Row: {
          created_at: string
          id: string
          inhalt: string
          kategorie: string
          tags: string[] | null
          thema: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          inhalt: string
          kategorie: string
          tags?: string[] | null
          thema: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          inhalt?: string
          kategorie?: string
          tags?: string[] | null
          thema?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

// Admin auth types — used across admin components and server-side auth guards.
import type { User } from '@supabase/supabase-js'

// Minimal representation of an authenticated admin user.
// The full Supabase User type satisfies this constraint.
export interface AdminUser {
  id: string
  email: string
}

// Re-export the full Supabase User type for use in auth utilities.
export type { User }

// ---------------------------------------------------------------------------
// Wissensfundus (knowledge base) types
// ---------------------------------------------------------------------------

// Matches the wissensfundus table row shape exactly.
export interface Wissensfundus {
  id: string
  kategorie: string
  thema: string
  inhalt: string
  tags: string[]
  created_at?: string
  updated_at?: string
}

// Shape of the form while the user is editing (tags stored as comma-separated string).
// Converted to the DB/action shape before submission.
export interface WissensfundusFormData {
  kategorie: 'sterbegeld' | 'pflege' | 'leben' | 'unfall' | 'allgemein'
  thema: string
  inhalt: string
  // Comma-separated string as the user types; converted to string[] before server action call.
  tags: string
}

// Typed return value for all server actions.
// fieldErrors mirrors Zod's flatten().fieldErrors shape.
export interface ActionResult {
  success: boolean
  error?: string
  fieldErrors?: Record<string, string[]>
}

// ---------------------------------------------------------------------------
// Produkt types
// ---------------------------------------------------------------------------

// Union types for all enum fields — used in schema validation and form controls.
export type ProduktTyp = 'sterbegeld' | 'pflege' | 'leben' | 'unfall'
export type ProduktStatus = 'entwurf' | 'aktiv' | 'archiviert'
export type Fokus = 'sicherheit' | 'preis' | 'sofortschutz'

// Matches the produkte table row shape.
export interface Produkt {
  id: string
  slug: string
  name: string
  typ: ProduktTyp
  status: ProduktStatus
  domain?: string | null
  created_at?: string
  updated_at?: string
}

// Matches the produkt_config table row shape.
export interface ProduktConfig {
  id: string
  produkt_id: string
  zielgruppe?: string[] | null
  fokus?: Fokus | null
  anbieter?: string[] | null
  argumente?: Record<string, string> | null
  created_at?: string
  updated_at?: string
}

// Combined shape used as initialData prop in ProduktForm.
// Composes the produkte row with an optional produkt_config row.
export interface ProduktWithConfig extends Produkt {
  produkt_config?: ProduktConfig | null
}

// ---------------------------------------------------------------------------
// Generierter Content types
// ---------------------------------------------------------------------------

// Mirrors the generierter_content table row with typed enum fields.
export interface GenerierterContent {
  id: string
  produkt_id: string
  page_type: 'hauptseite' | 'faq' | 'vergleich' | 'tarif' | 'ratgeber'
  slug?: string | null
  title?: string | null
  meta_title?: string | null
  meta_desc?: string | null
  content?: Record<string, unknown> | null
  schema_markup?: Record<string, unknown> | null
  status: 'entwurf' | 'review' | 'publiziert'
  generated_at?: string
  published_at?: string | null
  created_at?: string
  updated_at?: string
}

// ---------------------------------------------------------------------------
// Lead types
// ---------------------------------------------------------------------------

// Matches the leads table row shape exactly.
// Used in the Confluence client and lead capture API route.
export interface Lead {
  id: string
  produkt_id?: string | null
  vorname?: string | null
  nachname?: string | null
  email: string
  telefon?: string | null
  interesse?: string | null
  zielgruppe_tag?: string | null
  intent_tag?: string | null
  confluence_page_id?: string | null
  confluence_synced: boolean
  resend_sent: boolean
  created_at?: string
}
